### ISSUE TITLE
运行train_seg_edg.py时出现问题

### ISSUE THREAD

**Issue by panwangtao** [yyl558/SegNet-edg#1]
前面的步骤运行成功，在运行train_seg_edg.py文件时报错，主要问题是Resnet没有定义，运行结果如下
cuda:0
1
Traceback (most recent call last):
  File "E:/Iss/bc/SegNet-edg-main/train_seg_edg.py", line 143, in <module>
    main()
  File "E:/Iss/bc/SegNet-edg-main/train_seg_edg.py", line 31, in main
    model = SegNet_Edge()
  File "E:\Iss\bc\SegNet-edg-main\seg_edge.py", line 102, in __init__
    self.res1 = Resnet.BasicBlock(32, 32, stride=1)
NameError: name 'Resnet' is not defined

**Comment by suzhipeng1995** [comment]
解决了吗

**Comment by yyl558** [comment]
忘记上传 稍后补上------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月8日(星期四) 下午3:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [yyl558/SegNet-edg] 运行train_seg_edg.py时出现问题 (#1)

**Comment by suzhipeng1995** [comment]
谢谢

**Comment by Fuzhaojin** [comment]
您好，依据您给的数据集，我在跑代码的时候，在train_seg_edg.py中的损失位置报错，我不太懂如何解决。

**Comment by yyl558** [comment]
>

**Comment by yyl558** [comment]
> 什么错误

**Comment by yyl558** [comment]
什么错误




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yyl558/SegNet-edg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月23日(星期三) 中午12:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yyl558/SegNet-edg] 运行train_seg_edg.py时出现问题 (#1)





 
您好，依据您给的数据集，我在跑代码的时候，在train_seg_edg.py中的损失位置报错，我不太懂如何解决。

**Comment by Fuzhaojin** [comment]
main_loss.backward()
File"D: DeepStudyAnacondaB\envs(pytonch\lib\site-packages\tonch\tensor.py",line 118, in backwardtorch.autograd.backward(self,gradient,retain_graph，create_graph)
File "D:\DeepStudy\Anacondea3\envs\pytonch\lib\site-packages\torchlautogradl\..init ..py",，line 93,in backwardallow_unreachable=True)#t allow_unreachable flag
RuntimeError: cUDNN error:CUDNN_STATUS_NOT_INITIALIZED

**Comment by yyl558** [comment]
你的环境配置的都正确吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yyl558/SegNet-edg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月23日(星期三) 下午2:10
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [yyl558/SegNet-edg] 运行train_seg_edg.py时出现问题 (#1)





 
main_loss.backward()
 File"D: DeepStudyAnacondaB\envs(pytonch\lib\site-packages\tonch\tensor.py",line 118, in backwardtorch.autograd.backward(self,gradient,retain_graph，create_graph)
 File "D:\DeepStudy\Anacondea3\envs\pytonch\lib\site-packages\torchlautogradl..init ..py",，line 93,in backwardallow_unreachable=True)#t allow_unreachable flag
 RuntimeError: cUDNN error:CUDNN_STATUS_NOT_INITIALIZED
